# Generated by Django 4.2.13 on 2024-05-30 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
    ]
