# Generated by Django 4.2.13 on 2024-05-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=13, verbose_name='User contact phone number'),
        ),
    ]
