# Generated by Django 4.2.13 on 2024-05-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
