# Generated by Django 4.2.13 on 2024-05-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of the article')),
                ('spoiler', models.CharField(default='default spoiler', max_length=200, verbose_name='Text for preview of the article')),
                ('cover', models.ImageField(upload_to='', verbose_name='Cover image for article')),
                ('author', models.CharField(max_length=50, verbose_name='Author name')),
                ('text', models.TextField(verbose_name='Full text of the article')),
                ('date', models.DateField(verbose_name='Date on which article was posted')),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
            },
        ),
    ]
