# Generated by Django 4.2.13 on 2024-05-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_vacancy_options_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
