# Generated by Django 4.2.13 on 2024-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coupons_delete_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
