# Generated by Django 4.2.13 on 2024-05-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(default='workers_images.18601.png', upload_to='workers_images/'),
        ),
    ]
