# Generated by Django 4.2.13 on 2024-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[{'Admin', 'admin'}, {'worker', 'Worker'}, {'Customer', 'customer'}], default='idk', max_length=20),
        ),
    ]
