# Generated by Django 4.2.13 on 2024-05-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_cart_products_cart_created_at_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.FloatField(default=0),
        ),
    ]
