# Generated by Django 4.2.13 on 2024-09-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('history', models.TextField()),
                ('details', models.TextField()),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
