# Generated by Django 4.2.13 on 2024-09-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='video_url',
        ),
        migrations.AddField(
            model_name='company',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
