# Generated by Django 4.2.13 on 2024-09-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_company_video_url_company_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='certificate',
            field=models.TextField(),
        ),
    ]
