# Generated by Django 4.2.13 on 2024-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_company_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='smalldescription',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
