# Generated by Django 4.2.13 on 2024-09-27 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_vacancy_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
