# Generated by Django 4.2.13 on 2024-10-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
